private:
  endpoint: ${endpoint}
  endpoint_internal: ${endpoint_internal}
  accessKeyId: ${accessKeyId}
  accessKeySecret: ${accessKeySecret}
  bucketName: ems-manage
  rootPath: projectDocument
  sign: true